### PR TITLE
Dev healthy food predictor #89

### PR DESCRIPTION
**Pull request by barkhaaroraa**
## Related Issue

- Info about the related issue

- [x] GSSOC Participant
- [x] Contributor

Closes: ##89

### Describe the changes you've made
made a healthy food or not predictor using random forests model
## Type of change

used a dataset from kaggle and trained the model to predict whether the food is healthy or not

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

printed the rmse,r2 etc values

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by barkhaaroraa** [comment]
@adithya-s-k could you please look into this, if there's anything that needs to be improved upon please lmk

**Comment by barkhaaroraa** [comment]
Hi @adithya-s-k @miraj0507 @poorvika11 please look into it, it's been over 3 weeks now

**Comment by miraj0507** [comment]
With the new instructions kindly add a screenshot of your accuracy and the metric used , justwriting the model doesn't help.

**Comment by barkhaaroraa** [comment]
hi I've added the necessary changes please check

**Comment by barkhaaroraa** [comment]
@miraj0507 I've added the screenshots please add the labels to pr and merge

**Pull request merged**
