### PR TITLE
Tuberculosis Detection from X-ray Images

### PR DESCRIPTION
**Pull request by anupammaurya6767**
#15 Issue Resolved
- Added Tuberculosis Detection from X-ray Images Project
- Issue Resolved under GSSOC 23

### CODE REVIEW

**Review by adithya-s-k — CHANGES_REQUESTED** [review]
Please follow the project structure as mentioned above

**Comment by anupammaurya6767** [comment]
@adithya-s-k the dataset.md part i mentioned it in the ipynb file itself rest I will do that

**Comment by adithya-s-k** [comment]
its better to have a dataset.md file.
it will be easier to see and access if some one wants to replicate your project

**Comment by anupammaurya6767** [comment]
@adithya-s-k ok will do that

**Comment by adithya-s-k** [comment]
@anupammaurya6767 are there any updates👍👍

**Pull request merged**
