### PR TITLE
AI Image Search System Added

### PR DESCRIPTION
**Pull request by ayush-09**
## Related Issue
#12 
- Info about the related issue

- [x] GSSOC Participant
- [x] Contributor

Closes: #issue number that will be closed through this PR

### Describe the changes you've made
I made a AI Image Search System Model

Give a clear description what modifications you have made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| Original Screenshot | Updated Screenshot |
Screenshot (24)

### CODE REVIEW

**Comment by ayush-09** [comment]
@miraj0507 @adithya-s-k Please review this PR

**Comment by miraj0507** [comment]
Why is the model accuracy just 10%

**Comment by miraj0507** [comment]
out of 10 times only 1 time the model will predict right and the rest will show wrong?

**Comment by ayush-09** [comment]
@miraj0507 this is because of sparse accuracy. Okk i will use normal model accuracy and update it

**Comment by ayush-09** [comment]
@miraj0507 Please add a level as well

**Comment by ayush-09** [comment]
@adithya-s-k Please add level in this PR

**Pull request merged**
