### PR TITLE
Game of thrones personality matcher (closes #47)

### LINKED ISSUE #47: [PROJECT PROPOSAL]
## Project Request

---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | This is a project based on data science and machine learning which used TSNE algorithm and the main aim of this project is to match the personality of the game of thrones characters and this app is hosted on streamlit framework in pycharm IDE|
| Github | Abhinavcode13                |
| Email  | abhinavkumar130503@gmail.com                                  |
| Label  | GSSoC 23                  |

---

**Define You**

- [✔️ ] GSSOC Participant
- [✔️] Contributor

# Game of thrones personality matcher

## Description

This is a project based on data science and machine learning which used TSNE algorithm and the main aim of this project is to match the personality of the game of thrones characters and this app is hosted on streamlit framework in pycharm IDE|

## Timeline
In 3 days

image

### PR DESCRIPTION
**Pull request by Abhinavcode13**
## Related Issue #47 

- This is a project based on data science and machine learning which used TSNE algorithm and the main aim of this project is to match the personality of the game of thrones characters and this app is hosted on streamlit framework in pycharm IDE

- [✔️ ] GSSOC Participant
- [✔️] Contributor

Closes: #issue number that will be closed through this PR

### Describe the changes you've made
Added the following files:
-app.py
-demo.png
-game_of_thrones_perosnality_matcher.ipynb
-data.pkl
-README.md

## Type of change

What sort of change have you made:

- [✔️ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

The above code is tested by making app.py file and running it on streamlit.

## Checklist:

- [✔️ ] My code follows the guidelines of this project.
- [✔️ ] I have performed a self-review of my own code.
- [✔️ ] I have commented my code, particularly wherever it was hard to understand.
- [✔️ ] I have made corresponding changes to the documentation.
- [✔️ ] My changes generate no new warnings.
- [✔️ ] I have added tests that prove my fix is effective or that my feature works.
- [✔️ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
image

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
Please merge the PR @adithya-s-k  i have followed all the contributing guidelines and added the readme file to it.

**Review by adithya-s-k — CHANGES_REQUESTED** [review]
Everything is perfect but please follow this template for the readme of the project
 [project readme template
](https://github.com/CognitiveLab-tech/World-of-AI/blob/main/.github/project_readme_template.md)


also is it possible to record the project convert it into a gif and add it in a readme.

**Comment by Abhinavcode13** [comment]
Hey thanks for letting know me this where to make this changes @adithya-s-k ??

**Comment by Abhinavcode13** [comment]
So i just have to add a readme file considering project readme template is it?

**Review by Abhinavcode13 — COMMENTED** [review]
please review the changes now , I updated it

**Comment by Abhinavcode13** [comment]
Please review the changes @adithya-s-k

**Comment by Abhinavcode13** [comment]
hello @adithya-s-k can you merge this PR kindly , waiting from long time what's the update?

**Comment by Abhinavcode13** [comment]
@adithya-s-k any update?

**Comment by miraj0507** [comment]
With the new instructions kindly add a screenshot of your accuracy and the metric used, just writing the model doesn't help.

**Comment by Abhinavcode13** [comment]
@miraj0507 bro do you get what i made?

**Comment by Abhinavcode13** [comment]
@miraj0507 its a personality matcher , how can i add a accuracy graph . just take a look

**Comment by miraj0507** [comment]
That is a mass mailer to all the PR’s most are a model so accuracy is there
, if that doesn’t fit yours kindly ignore that.
It’s just the format they want so that needs to be followed. You can ignore
!
Ask @admin who is reviewing your project

**Comment by Abhinavcode13** [comment]
@miraj0507 admin not active

**Pull request closed without merging**
