### PR TITLE
[ML category based PROJECT PROPOSAL]-Early heart disease

### PR DESCRIPTION
**Pull request by poorvika11**
## Related Issue
#[ML category based PROJECT PROPOSAL] #9
- Developing a model to predict early heart disease prediction by doing a comparitive analysis of different machine learning models to predcit heart disease with highest accuracy on defined and most important attributes
- [x] GSSoC Participant
- [x] Contributor

Closes: #9

### Describe the changes you've made

A new folder consisting of Dataset of heart disease patient, Model file consisting of all models running on the dataset and a README file to understand what project is doing has been added to the branch.

The project involved analysis of the heart disease patient dataset with proper data processing. Then, different models was trained and predictions made with different algorithms KNN, Decision Tree, Random Forest,SVM,Logistic Regression etc. Variety of Machine Learning algorithms implemented in Python to predict the presence of heart disease in a patient. This is a classification problem, with input features as a variety of parameters, and the target variable as a binary variable, predicting whether heart disease is present or not.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

This feature is satisfying the ML related projects described under World-of-AI README file.

## How Has This Been Tested?

Different algorithms has been tested over the training dataset and validate the prediction over the testing dataset. The most accurate algorithms among  KNN, Decision Tree, Random Forest,SVM,Logistic Regression is Random Forest with 95%.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

image

### CODE REVIEW

**Comment by poorvika11** [comment]
@adithya-s-k look into the request and feel free to share if you have any issues.

**Comment by poorvika11** [comment]
Ohkay, I will update it.

**Comment by adithya-s-k** [comment]
sure thing
also @poorvika11 the project structure has changed a little bit
please make sure you put your project under the machine learning folder

**Comment by poorvika11** [comment]
Can you please share the link of the appropriate structure?

**Comment by adithya-s-k** [comment]
> Can you please share the link of the appropriate structure?

the project will be under the machine_learning folder 
that's the only change

**Comment by poorvika11** [comment]
Ohkay

**Comment by poorvika11** [comment]
@adithya-s-k I have made another PL with all the changes included i.e. README file, branch folder and images set.

**Comment by adithya-s-k** [comment]
@poorvika11 shall i close this PR?

**Pull request closed without merging**
